#!/bin/bash

./Log ${ORACLEPOSITPATH}/LogOracle
./Log2 ${ORACLEPOSITPATH}/Log2Oracle
./Log10 ${ORACLEPOSITPATH}/Log10Oracle
./Exp ${ORACLEPOSITPATH}/ExpOracle
./Exp2 ${ORACLEPOSITPATH}/Exp2Oracle
./Exp10 ${ORACLEPOSITPATH}/Exp10Oracle
./Sinh ${ORACLEPOSITPATH}/SinhOracle
./Cosh ${ORACLEPOSITPATH}/CoshOracle

